### ISSUE TITLE
Webp画像の表示について

### ISSUE THREAD

**Issue by x200b** [yukkuri-chabangeki/334mix.com#5]
現在`<img>`タグのsrc属性にWebp画像を指定していると思いますが、追加でonerror属性を指定してpng画像等を指定すれば非対応ブラウザでも表示が可能となると思います。

例：
`<img src="test.webp" onerror="this.src='test.png';">`

**Comment by WinLinux1028** [comment]
githubのリポジトリは1GB超えると警告くるので､なるべくファイルサイズを小さくしようとWebPにしています｡
それしたら意味がありません()

**Comment by lovetwice1012** [comment]
SVG使えばいい話のように見えます

**Comment by WinLinux1028** [comment]
普通の画像からsvgに変換することって出来なくない...?

**Comment by lovetwice1012** [comment]
ggったらそこそこ出てくるし過去にやったことあるのでできると思いますよ

**Comment by WinLinux1028** [comment]
そういう系のツールつかって変換してみたけど､中身はbase64でエンコードされたPNGですた
![image](https://user-images.githubusercontent.com/68107676/169730720-b5934f66-db48-45de-badc-132aa6d59539.png)

**Comment by lovetwice1012** [comment]
🤔
じゃあ難しそうですね...
変換の意味ねぇ.....

**Comment by WinLinux1028** [comment]
AIで変換するようなやつはあったけどダウンロードするには金払えってやつばっかだな

**Comment by x200b** [comment]
`ZUN.webp`を使って実験させて頂きましたが、
元ファイル：13 KB
JPEGファイル：12 KB
PNGファイル：20 KB
GIFファイル：16 KB
となりました。
`nicovideo.webp`も同様の傾向でWEBP 22 KB → JPEG 22 KBとなりました。

**Comment by ZOI-dayo** [comment]
Adobe illustrator持ってるのでやってみましょうか?

**Comment by ZOI-dayo** [comment]
<img width="778" alt="スクリーンショット 2022-05-23 15 45 34" src="https://user-images.githubusercontent.com/64856587/169759601-73729e83-4f27-4fc1-a5ee-7a03b301ced6.png">
だめですね
SVG化すると粘土みたいになる
